const attractionRows=[
["臺北市","台北101","Taipei 101","official","architecture","站在信義路五段、101 東北側人行道，以路面引導線對準塔尖仰拍","Stand northeast on Xinyi Road and align the street lines with the tower tip"],
["臺北市","象山六巨石","Xiangshan Six Boulders","official","city","從六巨石下方平台低角度拍，讓人物靠右、101 落在左側三分線","Shoot low from below the boulders, placing the subject right and Taipei 101 on the left third"],
["臺北市","四四南村","44 South Village","viral","architecture","在眷村草坪西側蹲低，用老屋屋瓦當前景框住台北101","Crouch on the west lawn and frame Taipei 101 with the old tiled roofs"],
["新北市","九份老街","Jiufen Old Street","official","history","站在阿妹茶樓對面階梯轉角，直幅收進紅燈籠、茶樓與山城層次","Use the stairway corner opposite A-Mei Teahouse for a vertical lantern-and-hillside composition"],
["新北市","野柳女王頭","Yehliu Queen's Head","official","coast","在步道標示拍攝點略微蹲低，讓女王頭側面輪廓避開後方人群","Crouch slightly at the marked viewpoint to isolate the Queen's Head profile from the crowd"],
["新北市","十分瀑布","Shifen Waterfall","official","nature","使用第二觀景台正面拍攝，慢快門保留瀑布絲滑水流與完整岩壁","Use the second viewing deck head-on with a slower shutter for silky water and the full cliff"],
["基隆市","和平島地質公園","Heping Island Geopark","official","coast","從阿拉寶灣外側步道向東拍，利用豆腐岩紋理把視線帶向海平面","Shoot east from the outer trail, using tofu-rock textures as leading lines to the horizon"],
["基隆市","正濱漁港彩色屋","Zhengbin Fishing Harbor","viral","architecture","站在中正路觀景平台正中央，長焦壓縮整排彩色屋與港內倒影","Stand centered on the Zhongzheng Road platform and use a telephoto to compress houses and reflections"],
["基隆市","望幽谷","Wangyou Valley","viral","nature","在稜線步道第一個轉彎回拍，讓S形步道穿過草坡通往海灣","Look back from the first ridge bend so the S-shaped path leads through grass toward the bay"],
["桃園市","大溪老街","Daxi Old Street","official","history","站在和平路中央安全停等區，以長焦正面壓縮連續牌樓立面","Use a telephoto from a safe pause point on Heping Road to compress the ornate façades"],
["桃園市","許厝港濕地","Xucuogang Wetland","official","nature","從木棧道末端朝西拍，低機位讓水面倒影占畫面下半部","Shoot west from the boardwalk end, keeping the camera low so reflections fill the lower half"],
["桃園市","虎頭山環保公園","Hutoushan Environmental Park","viral","city","在圓形觀景台南緣用長焦拍桃園城市天際線，藍調時刻最有層次","Use a telephoto from the south edge of the round deck for layered city lights at blue hour"],
["新竹市","南寮漁港魚鱗天梯","Nanliao Fish Scale Steps","official","coast","站在堤防上方45度斜拍，讓弧形階梯重複排列並留一位人物作比例","Shoot down at 45 degrees so the curved steps repeat, with one person for scale"],
["新竹市","新竹都城隍廟","Hsinchu City God Temple","official","history","從廟埕外側低角度拍牌樓，等待香客穿過形成生活感前景","Shoot the gate low from the outer plaza and wait for a passerby to add everyday context"],
["新竹市","香山濕地賞蟹步道","Xiangshan Wetland Boardwalk","official","nature","退潮時從岸端以長焦拍S形步道，夕陽方向可同時收進人影剪影","At low tide, use a telephoto from shore to compress the S-curve and sunset silhouettes"],
["新竹縣","內灣老街與吊橋","Neiwan Old Street & Bridge","official","history","從內灣吊橋南端回拍，利用鋼索線條引導至老街山景","Look back from the south end of the bridge, using cables to lead toward the mountain town"],
["新竹縣","司馬庫斯巨木群","Smangus Sacred Trees","viral","nature","站在巨木步道外緣仰拍，超廣角納入樹根與樹冠，人物置於底部比例","Shoot upward from the trail edge with an ultra-wide lens, including roots, canopy and a tiny figure"],
["新竹縣","新月沙灣","Crescent Bay","viral","coast","日落前站在潮線後方低角度拍水面反光，人物沿海岸線行走","Shoot low behind the tide line before sunset, with the subject walking along the reflective shore"],
["苗栗縣","龍騰斷橋","Longteng Broken Bridge","official","history","從南斷橋觀景平台使用中長焦，讓磚拱遺構與綠色山壁疊合","Use a mid-telephoto from the south platform to layer brick arches against the green hillside"],
["苗栗縣","崎頂子母隧道","Qiding Railway Tunnels","official","history","站在隧道口中央偏側，以拱形洞口形成畫框並保留出口亮部細節","Stand just off-center inside the portal and use the arch as a frame while preserving highlights"],
["苗栗縣","火炎山觀景點","Huoyanshan Viewpoint","viral","nature","從合法步道觀景缺口以長焦側拍惡地稜線，清晨斜光最能表現紋理","Use a telephoto from the legal trail opening; morning side light reveals the badland ridges"],
["臺中市","高美濕地","Gaomei Wetlands","official","coast","木棧道末端朝西低角度拍風車與倒影，人物安排在三分線形成剪影","Shoot west and low from the boardwalk end, placing a silhouette on the third with turbines reflected"],
["臺中市","臺中國家歌劇院","National Taichung Theater","official","architecture","站在大廳曲牆交會處使用超廣角仰拍，讓洞穴曲線包圍人物","Use an ultra-wide lens where lobby curves meet, shooting upward so the architecture wraps the subject"],
["臺中市","審計新村","Shenji New Village","viral","architecture","在中央巷道蹲低，以招牌與植栽作前景，等人物走過亮色牆面","Crouch in the central lane, framing with signs and plants as a subject passes the colorful wall"],
["彰化縣","鹿港老街","Lukang Old Street","official","history","從摸乳巷外較寬處以長焦拍紅磚巷弄，人物置中增加縱深比例","Use a telephoto from the wider entrance to compress the red-brick alley with a centered subject"],
["彰化縣","八卦山大佛","Baguashan Great Buddha","official","architecture","從參佛道第一段階梯正中央低角度拍，利用石獅與階梯對稱構圖","Shoot low and centered on the first stair flight, using stone lions and steps symmetrically"],
["彰化縣","芳苑海空步道","Fangyuan Seaside Skywalk","viral","coast","退潮後從步道轉角回拍蚵田與採蚵牛車，長焦壓縮海岸紋理","At low tide, look back from the bend and compress oyster fields and ox carts with a telephoto"],
["南投縣","日月潭向山眺望平台","Sun Moon Lake Xiangshan","official","nature","站在懸臂平台左側，超廣角把平台曲線、湖面與遠山一次收進","Stand on the left of the cantilever and use an ultra-wide lens for its curve, lake and mountains"],
["南投縣","清境農場青青草原","Qingjing Farm","official","nature","從北端步道向南拍層疊山景，人物與綿羊安排在前景下三分之一","Shoot south from the north trail, placing people and sheep in the lower third below layered mountains"],
["南投縣","忘憂森林","Wangyou Forest","viral","nature","沿指定步道在水池邊低角度拍枯木倒影，陰天可避免明暗反差過大","Shoot low beside the pond from the marked trail; overcast light balances dead trees and reflections"],
["雲林縣","北港朝天宮","Beigang Chaotian Temple","official","history","站在廟埕入口用廣角正面拍，保留牌樓、香客與廟門三層景深","Use a wide lens from the plaza entrance to layer the arch, worshippers and temple doors"],
["雲林縣","成龍濕地","Chenglong Wetlands","official","nature","從藝術裝置旁朝西拍水面與電線桿倒影，夕陽後五分鐘色彩最均勻","Shoot west beside the art installations for pole reflections; color is most even just after sunset"],
["雲林縣","雲林布袋戲館","Yunlin Hand Puppet Museum","official","architecture","從中庭走廊斜角拍紅磚拱門，用重複門框形成深度與節奏","Shoot diagonally through the courtyard arcade, using repeated brick arches for depth and rhythm"],
["嘉義市","檜意森活村","Hinoki Village","official","history","在日式宿舍轉角以木窗作前景，人物走在石板路三分線位置","Frame from a Japanese dorm corner with wooden windows and place the subject on the stone-path third"],
["嘉義市","嘉義公園射日塔","Sun-Shooting Tower","official","city","從公園參道中央以長焦仰拍塔身，讓兩側樹木自然形成對稱畫框","Use a telephoto from the central approach, letting trees symmetrically frame the tower"],
["嘉義市","蘭潭月影潭心","Lantan Moon Reflection","viral","architecture","站在裝置西北側以廣角拍銀色網體，藍調時刻可同時保留天空與燈光","Use a wide lens from the northwest side; blue hour balances the silver structure and illumination"],
["嘉義縣","阿里山小笠原山","Alishan Ogasawara Mountain","official","nature","日出前站在第二層平台東側，用中長焦壓縮雲海、山脈與晨光","Before sunrise, use a mid-telephoto from the east side of the second deck to compress clouds and ridges"],
["嘉義縣","太平雲梯","Taiping Suspension Bridge","official","nature","從橋頭前方低角度拍鋼索對稱線，過橋後回拍可帶入嘉南平原","Shoot low at the entrance for symmetric cables; look back after crossing to include the plains"],
["嘉義縣","東石漁人碼頭","Dongshi Fisherman's Wharf","official","coast","從白色堤岸斜拍木棧道與海面，日落時讓人物成為簡潔剪影","Shoot diagonally from the white seawall across the boardwalk, turning a person into a clean sunset silhouette"],
["臺南市","安平樹屋","Anping Tree House","official","history","在二樓空橋轉角向下拍，利用榕樹根包覆牆面形成天然框景","Look down from the second-floor bridge corner, using banyan roots wrapping the walls as a natural frame"],
["臺南市","奇美博物館","Chimei Museum","viral","architecture","站在阿波羅噴泉前中軸線，用中長焦把雕像、噴泉與博物館壓縮對齊","Use a mid-telephoto on the central axis before Apollo Fountain to align statue, water and museum"],
["臺南市","井仔腳瓦盤鹽田","Jingzaijiao Tile-Paved Salt Fields","official","coast","夕陽前從鹽堆後方低角度拍，利用鹽田水面形成天空鏡像","Shoot low behind the salt mounds before sunset so the pans mirror the sky"],
["高雄市","駁二藝術特區","The Pier-2 Art Center","official","architecture","從大義倉庫群軌道旁低角度拍裝置藝術，舊鐵軌可作引導線","Shoot low beside the Dayi warehouse rails, using old tracks as leading lines toward public art"],
["高雄市","蓮池潭龍虎塔","Lotus Pond Dragon and Tiger Pagodas","official","architecture","從九曲橋入口以長焦拍雙塔對稱倒影，避開正午頂光","Use a telephoto at the zigzag bridge entrance for symmetric pagodas and reflections; avoid midday light"],
["高雄市","崗山之眼","Siaogangshan Skywalk Park","official","nature","站在提琴橋弧線內側以超廣角回拍，讓鋼索包住遠方城市與山景","Use an ultra-wide lens inside the violin-shaped curve so cables frame the distant city and hills"],
["屏東縣","鵝鑾鼻燈塔","Eluanbi Lighthouse","official","coast","從大草坪東南側低角度拍，讓白色燈塔落在藍天與草地交界三分線","Shoot low from the southeast lawn, placing the white lighthouse on the sky-and-grass third"],
["屏東縣","龍磐公園","Longpan Park","official","coast","站在安全護欄內沿草坡斜拍海岸線，廣角保留珊瑚礁台地與太平洋","Stay behind the barrier and shoot diagonally along the coast, keeping the reef plateau and Pacific wide"],
["屏東縣","海口港看海美術館","Kanhai Art Museum","viral","architecture","從候船室外側用廣角斜拍大片玻璃與海面，把人物放在建築轉角","Shoot wide from outside the terminal, pairing glass and sea with a subject at the building corner"],
["宜蘭縣","太平山見晴懷古步道","Jianqing Historic Trail","official","nature","站在舊鐵道路基轉彎處低拍，讓覆苔軌道引導視線進入霧林","Shoot low at a bend in the old rail bed, using mossy tracks to lead into the misty forest"],
["宜蘭縣","外澳沙灘","Waiao Beach","viral","coast","從沙灘北側用長焦拍龜山島，退潮水面可加入人物與島嶼倒影","Use a telephoto from the north beach toward Turtle Island; low-tide reflections add people and island"],
["宜蘭縣","伯朗咖啡館頭城城堡","Mr. Brown Castle Café","viral","architecture","從下層花園仰拍城堡塔樓，讓步道與扶手形成通往主體的引導線","Shoot upward from the lower garden, using paths and rails to lead toward the castle tower"],
["花蓮縣","七星潭","Qixingtan Beach","official","coast","站在礫石灘弧線內側用廣角向北拍，讓浪線斜切畫面並帶入清水斷崖","Use a wide lens from inside the pebble-beach curve, letting surf cut diagonally toward the cliffs"],
["花蓮縣","鯉魚潭","Liyu Lake","official","nature","從潭南碼頭向北用中焦拍，將小船置於前景、中央山脈放在背景","Shoot north from the south pier with a normal lens, placing a boat foreground against the mountains"],
["花蓮縣","石梯坪","Shitiping","official","coast","從環形步道低角度拍壺穴與海蝕平台，廣角讓岩石紋理延伸到海面","Shoot low from the loop trail, using a wide lens to extend pothole textures toward the sea"],
["臺東縣","三仙台","Sanxiantai","official","coast","從遊客中心側海灘用中長焦拍八拱橋，讓橋身完整橫跨海面","Use a mid-telephoto from the visitor-center beach so the eight-arch bridge spans the frame"],
["臺東縣","伯朗大道","Brown Boulevard","official","nature","站在金城武樹前方路側以長焦拍，讓筆直稻田道路通往中央山脈","Use a telephoto from the roadside near the Takeshi Kaneshiro Tree, leading the farm road into the mountains"],
["臺東縣","多良車站","Duoliang Station","viral","coast","從觀景平台東側用長焦等列車通過，讓紅色欄杆、鐵道與太平洋分層","Wait with a telephoto on the east platform for a train, layering red rail, tracks and Pacific"],
["澎湖縣","大菓葉柱狀玄武岩","Daguoye Basalt Columns","official","coast","從水池右側低角度拍玄武岩倒影，人物站在岩壁下方能表現尺度","Shoot low from the pool's right side for basalt reflections, adding a person below for scale"],
["澎湖縣","二崁聚落","Erkan Historic Village","official","history","從老宅巷口以中焦拍咾咕石牆，利用門框與盆栽增加前景層次","Use a normal lens from an alley entrance, layering coral-stone walls with doorframes and plants"],
["澎湖縣","奎壁山摩西分海","Kuibishan Geosite","viral","coast","在步道開放後從岸端較高處拍S形潮間帶，長焦避免人群過度分散","After the path opens, shoot the S-shaped tidal trail from higher ground with a telephoto to compress visitors"],
["金門縣","翟山坑道","Zhaishan Tunnel","official","history","站在A字型坑道入口內側以廣角拍，讓洞口水面倒影形成上下對稱","Use a wide lens just inside the A-shaped tunnel so its opening and water reflection form symmetry"],
["金門縣","莒光樓","Juguang Tower","official","architecture","從正前方草坪低角度拍，利用階梯與兩側樹木形成端正對稱構圖","Shoot low from the front lawn, using steps and flanking trees for formal symmetry"],
["金門縣","馬山觀測所","Mashan Observation Station","official","coast","從迷彩走廊末端以長焦拍海岸與對岸島嶼，門框可自然框景","Use a telephoto at the end of the camouflage corridor, framing the coast and distant islands in the doorway"],
["連江縣","芹壁聚落","Qinbi Village","official","history","從村落上方觀景台用中長焦斜拍，壓縮石屋、階梯與海灣層次","Use a mid-telephoto from the upper viewpoint to compress stone houses, stairs and bay"],
["連江縣","北海坑道","Beihai Tunnel","official","history","在搖櫓船轉彎處用廣角拍花崗岩洞壁與水面反光，保持相機穩定","Use a wide lens at the boat turn for granite walls and reflected water, keeping the camera steady"],
["連江縣","大坵島梅花鹿","Daqiu Island Deer","viral","nature","沿指定步道以中長焦平視拍鹿，不追逐、不餵食並保留環境背景","Use a mid-telephoto at eye level from the marked trail; never chase or feed deer, and retain habitat context"]
];

const attractionThemes={architecture:{zh:'建築線條',en:'Architecture',timeZh:'日出後 1 小時或藍調時刻',timeEn:'1 hour after sunrise or blue hour',lensZh:'16–35mm；遠景可用 70mm',lensEn:'16–35mm; 70mm for compression'},city:{zh:'城市夜景',en:'Cityscape',timeZh:'日落後 15–30 分鐘',timeEn:'15–30 minutes after sunset',lensZh:'24–70mm＋小腳架',lensEn:'24–70mm with a small tripod'},history:{zh:'人文老街',en:'Heritage',timeZh:'上午 8–10 點，避開人潮',timeEn:'8–10 am before crowds',lensZh:'24–50mm',lensEn:'24–50mm'},coast:{zh:'海岸風景',en:'Coast',timeZh:'日出／日落前後；先查潮汐',timeEn:'Around sunrise/sunset; check tides',lensZh:'16–35mm＋70–200mm',lensEn:'16–35mm plus 70–200mm'},nature:{zh:'自然山景',en:'Nature',timeZh:'清晨柔光或陰天',timeEn:'Soft early light or overcast',lensZh:'16–35mm；細節用長焦',lensEn:'16–35mm; telephoto for details'}};
const attractionImages={architecture:['https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?auto=format&fit=crop&w=1200&q=80'],city:['https://images.unsplash.com/photo-1470004914212-05527e49370b?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=1200&q=80'],history:['https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?auto=format&fit=crop&w=1200&q=80'],coast:['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1473116763249-2faaef81ccda?auto=format&fit=crop&w=1200&q=80'],nature:['https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1200&q=80']};
const attractions=attractionRows.map((r,id)=>({id,city:r[0],name:r[1],en:r[2],type:r[3],theme:r[4],shot:r[5],shotEn:r[6],image:attractionImages[r[4]][id%2]}));
const attractionCopy={zh:{title:'台灣景點與拍照機位',intro:'官方必遊景點加上網路熱門打卡地；每個景點都整理好拍攝站位、方向、時間與鏡頭建議。',search:'搜尋景點、縣市或拍攝主題…',city:'縣市',type:'景點類型',theme:'拍攝主題',allCity:'全部縣市',allType:'全部類型',allTheme:'全部主題',official:'官方景點',viral:'熱門打卡',result:'個景點與拍照機位',coverage:'涵蓋全台 22 縣市',reset:'清除篩選',detail:'查看拍照攻略',lead:'這個景點適合安排在台灣旅行路線中，也很適合用不同焦段觀察環境、人物與光線的關係。',angle:'推薦拍攝站位與角度',time:'最佳時間／光線',lens:'建議鏡頭',safety:'現場提醒',safetyText:'不跨越護欄、不妨礙通行；海岸先查潮汐，山區先看天候與開放公告。',map:'Google 地圖',searchWeb:'搜尋最新照片',note:'拍照角度為現場構圖建議；開放時間、交通、潮汐與管制可能變動，出發前請查官方公告。'},en:{title:'Taiwan sights & photo spots',intro:'Official attractions and popular online photo spots, each with a suggested position, direction, light and lens.',search:'Search sights, cities or photo themes…',city:'City / county',type:'Spot type',theme:'Photo theme',allCity:'All cities & counties',allType:'All types',allTheme:'All themes',official:'Official attraction',viral:'Popular photo spot',result:'sights & photo positions',coverage:'All 22 cities and counties',reset:'Reset filters',detail:'Open photo guide',lead:'A worthwhile stop on a Taiwan itinerary and a strong place to study how environment, people and light work across focal lengths.',angle:'Recommended position & angle',time:'Best time / light',lens:'Suggested lens',safety:'On-site reminder',safetyText:'Stay behind barriers and keep paths clear. Check tides on coasts and weather or closures in the mountains.',map:'Google Maps',searchWeb:'Find recent photos',note:'Angles are composition suggestions. Hours, access, tides and restrictions can change; check official notices before leaving.'}};

const categoryLabels={zh:{title:'想逛夜市，還是拍台灣？',market:'夜市導覽',attraction:'景點與拍照機位'},en:{title:'Night markets or photo spots?',market:'Night market guide',attraction:'Sights & photo positions'}};
const a$=s=>document.querySelector(s),aSearch=a$('#attractionSearch'),aCity=a$('#attractionCity'),aType=a$('#attractionType'),aTheme=a$('#attractionTheme');
function attractionLang(){return typeof lang==='string'?lang:(localStorage.getItem('nm-lang')||'zh')}
function setupAttractionFilters(){const l=attractionLang(),c=attractionCopy[l],current=[aCity.value,aType.value,aTheme.value];aCity.innerHTML=`<option value="">${c.allCity}</option>`+[...new Set(attractions.map(x=>x.city))].map(x=>`<option value="${x}">${l==='zh'?x:cityEn[x]}</option>`).join('');aType.innerHTML=`<option value="">${c.allType}</option><option value="official">${c.official}</option><option value="viral">${c.viral}</option>`;aTheme.innerHTML=`<option value="">${c.allTheme}</option>`+Object.entries(attractionThemes).map(([k,v])=>`<option value="${k}">${v[l]}</option>`).join('');[aCity.value,aType.value,aTheme.value]=current}
function attractionMap(a){return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(a.name+' '+a.city)}`}
function renderAttractions(){const l=attractionLang(),c=attractionCopy[l],q=aSearch.value.trim().toLowerCase(),list=attractions.filter(a=>(!aCity.value||a.city===aCity.value)&&(!aType.value||a.type===aType.value)&&(!aTheme.value||a.theme===aTheme.value)&&(!q||[a.name,a.en,a.city,cityEn[a.city],a.shot,a.shotEn,attractionThemes[a.theme].zh,attractionThemes[a.theme].en].join(' ').toLowerCase().includes(q)));a$('#attractionCount').textContent=list.length;a$('#attractionEmpty').hidden=list.length>0;a$('#attractionGrid').innerHTML=list.map(a=>{const theme=attractionThemes[a.theme];return `<article class="attraction-card"><div class="attraction-photo"><img src="${a.image}" alt="${l==='zh'?a.name:a.en}" loading="lazy"><span class="spot-badge ${a.type==='viral'?'viral':''}">${a.type==='official'?c.official:c.viral}</span><span class="spot-city">${l==='zh'?a.city:cityEn[a.city]}</span><div class="angle-preview">${l==='zh'?a.shot:a.shotEn}</div></div><div class="attraction-card-body"><h3>${l==='zh'?a.name:a.en}</h3><small>${l==='zh'?a.en:a.name}</small><p>${l==='zh'?`從${theme.zh}角度重新看見${a.name}，卡片內已整理最容易成功的構圖方式。`:`See ${a.en} through a ${theme.en.toLowerCase()} composition, with a practical setup inside.`}</p><div class="photo-meta"><span>${theme[l]}</span><span>${l==='zh'?'拍攝機位':'Photo position'}</span></div></div><div class="attraction-card-footer"><span>PHOTO GUIDE</span><button class="detail-btn" type="button" data-attraction-id="${a.id}">${c.detail} →</button></div></article>`}).join('')}
function updateAttractionLanguage(){const l=attractionLang(),c=attractionCopy[l],labels=categoryLabels[l];a$('#categoryTitle').textContent=labels.title;a$('#marketTabLabel').textContent=labels.market;a$('#attractionTabLabel').textContent=labels.attraction;a$('#attractionTitle').textContent=c.title;a$('#attractionIntro').textContent=c.intro;aSearch.placeholder=c.search;a$('#attractionCityLabel').textContent=c.city;a$('#attractionTypeLabel').textContent=c.type;a$('#attractionThemeLabel').textContent=c.theme;a$('#attractionResultText').textContent=c.result;a$('#attractionCoverage').textContent=c.coverage;a$('#attractionReset').textContent=c.reset;setupAttractionFilters();renderAttractions()}
function openAttraction(id,updateHash=true){const a=attractions.find(x=>x.id===id);if(!a)return;const l=attractionLang(),c=attractionCopy[l],t=attractionThemes[a.theme],map=attractionMap(a);a$('#attractionDetail').innerHTML=`<div class="attraction-detail-hero"><img src="${a.image}" alt="${l==='zh'?a.name:a.en}"><div class="attraction-hero-copy"><span>${a.type==='official'?c.official:c.viral} · ${l==='zh'?a.city:cityEn[a.city]}</span><h2 id="attractionDetailTitle">${l==='zh'?a.name:a.en}</h2><p>${l==='zh'?a.en:a.name}</p></div></div><div class="shooting-guide"><p class="eyebrow">PHOTO POSITION GUIDE</p><p class="shooting-lead">${c.lead}</p><div class="angle-callout"><span>⌖</span><div><small>${c.angle}</small><strong>${l==='zh'?a.shot:a.shotEn}</strong></div></div><div class="shooting-grid"><div class="guide-cell"><small>${c.time}</small><b>${l==='zh'?t.timeZh:t.timeEn}</b></div><div class="guide-cell"><small>${c.lens}</small><b>${l==='zh'?t.lensZh:t.lensEn}</b></div><div class="guide-cell"><small>${c.theme}</small><b>${t[l]}</b></div><div class="guide-cell"><small>${c.safety}</small><b>${c.safetyText}</b></div></div><div class="spot-actions"><a href="${map}" target="_blank" rel="noopener">${c.map} ↗</a><a class="secondary" href="https://www.google.com/search?tbm=isch&q=${encodeURIComponent(a.name+' 拍照角度')}" target="_blank" rel="noopener">${c.searchWeb} ↗</a></div><p class="source-note">ⓘ ${c.note}</p></div>`;a$('#attractionDialog').showModal();if(updateHash)history.pushState({attraction:id},'',`#attraction=${id}`)}

function showCategory(category){const marketsOn=category==='markets';a$('#explore').hidden=!marketsOn;a$('#tips').hidden=!marketsOn;a$('#attractions').hidden=marketsOn;a$('#marketTab').classList.toggle('active',marketsOn);a$('#attractionTab').classList.toggle('active',!marketsOn);a$('#marketTab').setAttribute('aria-selected',marketsOn);a$('#attractionTab').setAttribute('aria-selected',!marketsOn);localStorage.setItem('tw-category',category);if(!marketsOn)renderAttractions()}
document.querySelectorAll('.category-tab').forEach(btn=>btn.addEventListener('click',()=>{showCategory(btn.dataset.category);document.querySelector(btn.dataset.category==='markets'?'#explore':'#attractions').scrollIntoView({behavior:'smooth'})}));
[aSearch,aCity,aType,aTheme].forEach(el=>el.addEventListener(el===aSearch?'input':'change',renderAttractions));
a$('#attractionReset').addEventListener('click',()=>{aSearch.value='';aCity.value='';aType.value='';aTheme.value='';renderAttractions()});
a$('#attractionGrid').addEventListener('click',e=>{const b=e.target.closest('[data-attraction-id]');if(b)openAttraction(Number(b.dataset.attractionId))});
a$('#attractionClose').addEventListener('click',()=>{a$('#attractionDialog').close();history.replaceState(null,'',location.pathname+location.search)});a$('#attractionDialog').addEventListener('click',e=>{if(e.target===a$('#attractionDialog'))a$('#attractionClose').click()});
a$('#langToggle').addEventListener('click',()=>setTimeout(()=>{updateAttractionLanguage();if(a$('#attractionDialog').open)openAttraction(Number(a$('#attractionDialog').dataset.attractionId),false)},0));
const originalOpenAttraction=openAttraction;openAttraction=function(id,updateHash=true){a$('#attractionDialog').dataset.attractionId=id;originalOpenAttraction(id,updateHash)};
window.addEventListener('popstate',()=>{const m=location.hash.match(/^#attraction=(\d+)$/);if(m){showCategory('attractions');openAttraction(Number(m[1]),false)}else if(a$('#attractionDialog').open)a$('#attractionDialog').close()});
updateAttractionLanguage();showCategory(localStorage.getItem('tw-category')||'markets');const initialAttraction=location.hash.match(/^#attraction=(\d+)$/);if(initialAttraction){showCategory('attractions');openAttraction(Number(initialAttraction[1]),false)}
